[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
onchain_gmm_contracts = "FcXK2AuHYzE5fykqQj65955bvh5N2LojFkuoC8fz5nVw"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/rowla/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
